version: '3'

services:
  python:
    build: ./python
    container_name: python_stats
    tty: true
    volumes:
      - ./:/app
    entrypoint: jupyter notebook --notebook-dir="notebooks" --ip=0.0.0.0 --allow-root
    ports:
      - 8888:8888

  mongo:
    image: mongo:latest
    container_name: mongo_stats
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 8001:8001

  neo:
    image: neo4j:2.3.2
    container_name: neo_stats
    volumes:
      - ./data/neo:/db/data
    ports:
      - 7474:7474  # HTTP
      - 7473:7473  # HTTPS
      - 7687:7687  # Bolt
